<?php

namespace AppBundle\Repository;

/**
 * DealsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActivedeals()
    {
        $qb = $this->getEntityManager()
            ->createQuery("Select d from AppBundle:Deals d where d.active=1")
            ->getResult();
        return $qb ;
    }
}
