<?php

namespace AppBundle\Repository;

/**
 * LieuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuxRepository extends \Doctrine\ORM\EntityRepository
{


}
