<?php

namespace AppBundle\Repository;

/**
 * LikesArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
