<?php

namespace AppBundle\Repository;

/**
 * LikesPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
