<?php

namespace AppBundle\Repository;

/**
 * LikesPublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesPublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
